name: CDNet
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=11.8
  - networkx=3.2.1
  - jinja2=3.1.6
  - requests=2.32.5
  - pyyaml=6.0.2
  - filelock=3.17.0
  - typing_extensions=4.15.0
  - pip